[package]
name = "mnemeona"
version = "0.1.4"
description = "Mnemeona - AI-powered creative writing and worldbuilding"
authors = ["yixleex"]
edition = "2021"

[lib]
name = "mnemeona_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = [] }
