import { useEffect, useState } from "react"

import {
  Building2,
  Globe2,
  Landmark,
  MapPin,
  Mountain,
} from "lucide-react"

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

import type {
  Location,
  LocationType,
} from "@/types/world/location"

interface NewLocationDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void

  /**
   * Called with the completed location form.
   *
   * For a new location, the ID and timestamps are
   * generated by the project location actions.
   *
   * For an existing location, the existing ID is
   * preserved by LocationDatabase.
   */
  onCreate: (location: Location) => void

  location?: Location | null
}

const LOCATION_TYPES: LocationType[] = [
  "Continent",
  "Country",
  "Region",
  "City",
  "Town",
  "Village",
  "District",
  "Building",
  "Landmark",
  "Dungeon",
  "Battlefield",
  "Natural Feature",
  "Other",
]

interface LocationFormState {
  name: string
  type: LocationType
  description: string
  region: string
  climate: string
  population: string
  government: string
  significance: string
  history: string
  secrets: string
}

const EMPTY_FORM: LocationFormState = {
  name: "",
  type: "City",
  description: "",
  region: "",
  climate: "",
  population: "",
  government: "",
  significance: "",
  history: "",
  secrets: "",
}

function getLocationIcon(
  type: LocationType,
) {
  switch (type) {
    case "Continent":
    case "Country":
    case "Region":
      return Globe2

    case "City":
    case "Town":
    case "Village":
    case "District":
    case "Building":
      return Building2

    case "Landmark":
    case "Dungeon":
    case "Battlefield":
      return Landmark

    case "Natural Feature":
      return Mountain

    default:
      return MapPin
  }
}

export function NewLocationDialog({
  open,
  onOpenChange,
  onCreate,
  location,
}: NewLocationDialogProps) {
  const [form, setForm] =
    useState<LocationFormState>(
      EMPTY_FORM,
    )

  const isEditing =
    Boolean(location)

  // --------------------------------------------------
  // Load location into form
  // --------------------------------------------------

  useEffect(() => {
    if (!open) {
      return
    }

    if (location) {
      setForm({
        name: location.name,
        type: location.type,
        description:
          location.description,

        region:
          location.region ?? "",

        climate:
          location.climate ?? "",

        population:
          location.population ?? "",

        government:
          location.government ?? "",

        significance:
          location.significance ?? "",

        history:
          location.history ?? "",

        secrets:
          location.secrets ?? "",
      })
    } else {
      setForm({
        ...EMPTY_FORM,
      })
    }
  }, [
    open,
    location,
  ])

  // --------------------------------------------------
  // Form updates
  // --------------------------------------------------

  const updateField = <
    K extends keyof LocationFormState
  >(
    field: K,
    value: LocationFormState[K],
  ) => {
    setForm((current) => ({
      ...current,
      [field]: value,
    }))
  }

  // --------------------------------------------------
  // Submit
  // --------------------------------------------------

  const handleSubmit = () => {
    const name =
      form.name.trim()

    if (!name) {
      return
    }

    /*
     * The dialog does not generate IDs or timestamps.
     *
     * LocationDatabase decides whether this is a new
     * location or an existing one and passes the data
     * to ProjectContext.
     */

    const submittedLocation:
      Location = {
      id:
        location?.id ?? "",

      name,

      type:
        form.type,

      description:
        form.description.trim(),

      parentLocationId:
        location?.parentLocationId,

      region:
        form.region.trim() ||
        undefined,

      climate:
        form.climate.trim() ||
        undefined,

      population:
        form.population.trim() ||
        undefined,

      government:
        form.government.trim() ||
        undefined,

      significance:
        form.significance.trim() ||
        undefined,

      history:
        form.history.trim() ||
        undefined,

      secrets:
        form.secrets.trim() ||
        undefined,

      /*
       * These values are only required because the
       * Location type requires them.
       *
       * For new locations, LocationDatabase ignores
       * them and locationActions generates the real
       * values.
       *
       * For existing locations, the original values
       * are preserved.
       */
      createdAt:
        location?.createdAt ?? "",

      updatedAt:
        location?.updatedAt ?? "",
    }

    onCreate(
      submittedLocation,
    )

    onOpenChange(false)
  }

  const Icon =
    getLocationIcon(
      form.type,
    )

  return (
    <Dialog
      open={open}
      onOpenChange={
        onOpenChange
      }
    >
      <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>
            {isEditing
              ? "Edit Location"
              : "Create Location"}
          </DialogTitle>

          <DialogDescription>
            Define a place in your world and
            the details the AI should
            understand about it.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-2">
          {/* Basic Information */}

          <section className="space-y-4">
            <div>
              <h3 className="text-sm font-semibold">
                Basic Information
              </h3>

              <p className="text-xs text-muted-foreground">
                The identity and general
                description of this place.
              </p>
            </div>

            <div className="grid gap-4 sm:grid-cols-[1fr_180px]">
              <div className="space-y-2">
                <label
                  htmlFor="location-name"
                  className="text-sm font-medium"
                >
                  Name
                </label>

                <Input
                  id="location-name"
                  value={form.name}
                  onChange={(event) =>
                    updateField(
                      "name",
                      event.target.value,
                    )
                  }
                  placeholder="e.g. Blackwater Pass"
                  autoFocus
                />
              </div>

              <div className="space-y-2">
                <label
                  htmlFor="location-type"
                  className="text-sm font-medium"
                >
                  Type
                </label>

                <div className="relative">
                  <select
                    id="location-type"
                    value={form.type}
                    onChange={(event) =>
                      updateField(
                        "type",
                        event.target
                          .value as LocationType,
                      )
                    }
                    className="h-10 w-full appearance-none rounded-md border bg-background px-3 pr-9 text-sm"
                  >
                    {LOCATION_TYPES.map(
                      (type) => (
                        <option
                          key={type}
                          value={type}
                        >
                          {type}
                        </option>
                      ),
                    )}
                  </select>

                  <Icon className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                </div>
              </div>
            </div>

            <div className="space-y-2">
              <label
                htmlFor="location-description"
                className="text-sm font-medium"
              >
                Description
              </label>

              <Textarea
                id="location-description"
                value={
                  form.description
                }
                onChange={(event) =>
                  updateField(
                    "description",
                    event.target.value,
                  )
                }
                placeholder="Describe what this place is like..."
                rows={4}
              />

              <p className="text-xs text-muted-foreground">
                This is the primary description
                the AI can use when understanding
                the location.
              </p>
            </div>
          </section>

          {/* Geography */}

          <section className="space-y-4">
            <div>
              <h3 className="text-sm font-semibold">
                Geography & Environment
              </h3>

              <p className="text-xs text-muted-foreground">
                Describe where the location exists
                and its physical characteristics.
              </p>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <label
                  htmlFor="location-region"
                  className="text-sm font-medium"
                >
                  Region
                </label>

                <Input
                  id="location-region"
                  value={form.region}
                  onChange={(event) =>
                    updateField(
                      "region",
                      event.target.value,
                    )
                  }
                  placeholder="e.g. Northern Kingdoms"
                />
              </div>

              <div className="space-y-2">
                <label
                  htmlFor="location-climate"
                  className="text-sm font-medium"
                >
                  Climate / Environment
                </label>

                <Input
                  id="location-climate"
                  value={form.climate}
                  onChange={(event) =>
                    updateField(
                      "climate",
                      event.target.value,
                    )
                  }
                  placeholder="e.g. Cold, mountainous, snowy"
                />
              </div>
            </div>
          </section>

          {/* Society */}

          <section className="space-y-4">
            <div>
              <h3 className="text-sm font-semibold">
                Society
              </h3>

              <p className="text-xs text-muted-foreground">
                Information about the people and
                structures that exist here.
              </p>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <label
                  htmlFor="location-population"
                  className="text-sm font-medium"
                >
                  Population
                </label>

                <Input
                  id="location-population"
                  value={
                    form.population
                  }
                  onChange={(event) =>
                    updateField(
                      "population",
                      event.target.value,
                    )
                  }
                  placeholder="e.g. 25,000"
                />
              </div>

              <div className="space-y-2">
                <label
                  htmlFor="location-government"
                  className="text-sm font-medium"
                >
                  Government / Control
                </label>

                <Input
                  id="location-government"
                  value={
                    form.government
                  }
                  onChange={(event) =>
                    updateField(
                      "government",
                      event.target.value,
                    )
                  }
                  placeholder="e.g. Ruled by House Valen"
                />
              </div>
            </div>
          </section>

          {/* Story Context */}

          <section className="space-y-4">
            <div>
              <h3 className="text-sm font-semibold">
                Story Context
              </h3>

              <p className="text-xs text-muted-foreground">
                Details that make this location
                relevant to the story.
              </p>
            </div>

            <div className="space-y-2">
              <label
                htmlFor="location-significance"
                className="text-sm font-medium"
              >
                Significance
              </label>

              <Textarea
                id="location-significance"
                value={
                  form.significance
                }
                onChange={(event) =>
                  updateField(
                    "significance",
                    event.target.value,
                  )
                }
                placeholder="Why is this place important to the story?"
                rows={3}
              />
            </div>

            <div className="space-y-2">
              <label
                htmlFor="location-history"
                className="text-sm font-medium"
              >
                History
              </label>

              <Textarea
                id="location-history"
                value={
                  form.history
                }
                onChange={(event) =>
                  updateField(
                    "history",
                    event.target.value,
                  )
                }
                placeholder="Important historical events, origins, changes, or past inhabitants..."
                rows={4}
              />
            </div>

            <div className="space-y-2">
              <label
                htmlFor="location-secrets"
                className="text-sm font-medium"
              >
                Secrets
              </label>

              <Textarea
                id="location-secrets"
                value={
                  form.secrets
                }
                onChange={(event) =>
                  updateField(
                    "secrets",
                    event.target.value,
                  )
                }
                placeholder="Hidden information, mysteries, forbidden knowledge, or things characters may not know..."
                rows={4}
              />

              <p className="text-xs text-muted-foreground">
                Secrets can later be used to
                distinguish what the author knows
                from what characters know.
              </p>
            </div>
          </section>
        </div>

        <DialogFooter>
          <Button
            variant="outline"
            onClick={() =>
              onOpenChange(false)
            }
          >
            Cancel
          </Button>

          <Button
            onClick={handleSubmit}
            disabled={
              !form.name.trim()
            }
          >
            {isEditing
              ? "Save Changes"
              : "Create Location"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
